### ISSUE TITLE
Invalid PDF

### ISSUE THREAD

**Issue by EmreCelenli** [csunibo/logica-per-informatica#18]
Ciao, 

Non si può aprire questi PDF.

I path:
varie/00-dare-logica-logiche-counting-gerarchia-wagner-handout.pdf
varie/01-dare-logica-logiche-counting-gerarchia-wagner.pdf

Mi dà questo errore:
Error rendering embedded code
Invalid PDF

Buon lavoro,
Emre Kerem Celenli

**Comment by foxyseta** [comment]
Già sembrano PDF rotti. Sono stati caricati da me in https://github.com/csunibo/logica-per-informatica/commit/ab30843b11332339e2bb0c848a77587e6d678f25 e forse non li ho controllati? Comunque sono seminari di DARe Logica, che tiene il DAR a Unibo. @samuelemusiani io anziché chiedere di nuovo le copienli rimuoverei proprio perché non sono attinenti al corso.

**Comment by EmreCelenli** [comment]
Si, anche a me sembrano PDF rotti. Se volete, posso darvi una mano.

**Comment by foxyseta** [comment]
Massì dai siccome li ho caricati io (e quindi so che non c'entrano un tubo in realtà) e fino ad ora il problema non è mai stato segnalato assume che alla gente neanche interessino.

Sentiti pure libero di aprire una PR in cui li elimini e te la accettiamo a breve. :)

Se non sei già nel gruppo https://t.me/csunibo e ti va di entrare per vedere cosa facciamo co fa solo piacere sicuro.

**Comment by EmreCelenli** [comment]
Si, hai ragione. Ho aperto una PR e ho eliminato i PDF. 

Sono nel gruppo e ho visto quello che avete fatto. Sarebbe un piacere per me imparare con voi e lavorare con voi nei futuri progetti.

**Comment by foxyseta** [comment]
Ottimo! Se chiedi là sicuro ti sanno dire a quali progetti serve una mano al momento.
